adx_contentdisposition: 756150000
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: src-settings-constants.js
adx_parentpageid: ad963c6d-0123-4433-857d-d28ae429b6c9
adx_partialurl: src-settings-constants.js
adx_publishingstateid: a53eb8e0-8b05-43be-b58e-f7f9dc37c71d
adx_webfileid: 2fc36dae-d3bd-f011-bbd2-7ced8da63393
annotationid: 8a50b5e9-d3bd-f011-bbd2-7ced8da63393
filename: src-settings-constants.js
isdocument: true
mimetype: application/javascript
objectid: 2fc36dae-d3bd-f011-bbd2-7ced8da63393
objecttypecode: adx_webfile
